version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "art_of_life"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: